name = "nyc-properties-hub"
compatibility_date = "2024-09-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "properties-hub"
database_id = "86dff9c1-0603-40b1-ac04-e81340fe83b9"

[[r2_buckets]]
binding = "FILES"
bucket_name = "properties-hub-files"

[vars]
FILES_PUBLIC_BASE = "https://pub-4f7ef8819e6641dfa6ff1d93f52051d0.r2.dev"
